partials:
  - name: about_me
    title: 'AboutMe'
    avatar: '5ee0e6a0b17d8fa6.png'  # = /static/upload/me.jpg
    intro: '你看到了我哟~'
    sns:
    - github: 'LouisYZK'
    - douban: 'example'
    # - linkedin: 'example'
    # - instagram: 'example'
    # - stack-overflow: 'example'
    # - medium: 'example'
    - zhihu: 'louis-young-23'
    - email: 'example'
    # - wechat: 'wechat-qrcode.jpg'
    # - weixingongzhonghao: 'wechat-subscription-account-qrcode.png'
  - name: tagcloud
    title: 标签云
    count: 20
  - name: html
    title: Status
    body: |
      <p>疯狂 <strong>打码中</strong>!!</p>
  # - name: latest_comments
  #   title: 最新评论
  #   count: 5
  #   max_length: 65
  - name: blogroll
    title: 友情链接
    links:
      - title: '学术版个人空间'
        url: 'https://louisyzk.github.io/'

  # - name: most_viewed
  #   title: '最热文章'
  #   count: 5
